# Generated by Django 5.0.6 on 2024-06-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_galpal', '0002_interests_matchprofilequestions_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.CreateModel(
            name='MatchProfileDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30, null=True)),
                ('bio', models.TextField(max_length=300, null=True)),
                ('city', models.TextField(blank=True, max_length=300, null=True)),
                ('state', models.TextField(blank=True, max_length=300, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('answers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_galpal.matchprofileanswers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to='app_galpal.profile')),
            ],
        ),
    ]
