# Generated by Django 5.0.6 on 2024-06-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_galpal', '0005_remove_matchprofiledisplay_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechannel',
            name='user',
        ),
        migrations.AddField(
            model_name='messagechannel',
            name='user1',
            field=models.ManyToManyField(related_name='user1', to='app_galpal.profile'),
        ),
        migrations.AddField(
            model_name='messagechannel',
            name='user2',
            field=models.ManyToManyField(related_name='user2', to='app_galpal.profile'),
        ),
        migrations.RemoveField(
            model_name='friendslist',
            name='friend',
        ),
        migrations.AddField(
            model_name='friendslist',
            name='friend',
            field=models.ManyToManyField(related_name='user_friends', to='app_galpal.profile'),
        ),
    ]
